[package]
name = "sc-mpc"
version = "2.0.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"

[dependencies]
primitives = { package = "sp-core",  path = "../../primitives/core" }
app-crypto = { package = "sc-application-crypto",  path = "../../primitives/application-crypto"}
